name: CI Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "erroranalysis/**"
      - "rai_test_utils/**"
      - "raiutils/**"
      - "responsibleai/**"
      - ".github/workflows/CI-python.yml"

jobs:
  ci-python:
    strategy:
      matrix:
        packageDirectory:
          ["responsibleai", "erroranalysis", "raiutils", "rai_test_utils"]
        operatingSystem: [ubuntu-latest, macos-latest, windows-latest]
        pythonVersion: ["3.9", "3.10", "3.11"]
        exclude:
          - packageDirectory: "responsibleai"
            pythonVersion: "3.11"
          - packageDirectory: "responsibleai"
            operatingSystem: "macos-latest"
            pythonVersion: "3.9"

    runs-on: ${{ matrix.operatingSystem }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.pythonVersion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Setup tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade "pip-tools<=7.1.0"

      - if: ${{ matrix.operatingSystem == 'macos-latest' }}
        name: Use Homebrew to install libomp on MacOS
        run: |
          brew install libomp

      - name: Install package dependencies
        run: |
          pip install -r requirements-dev.txt
        working-directory: ${{ matrix.packageDirectory }}

      - name: Install package
        run: |
          pip install -v -e .
        working-directory: ${{ matrix.packageDirectory }}

      - name: Pip freeze
        run: |
          pip freeze > installed-requirements-dev.txt
          cat installed-requirements-dev.txt
        working-directory: raiwidgets

      - if: ${{ (matrix.operatingSystem == 'windows-latest') && (matrix.pythonVersion == '3.9') && (matrix.packageDirectory == 'responsibleai') }}
        name: Upload requirements
        uses: actions/upload-artifact@v4
        with:
          name: requirements-dev.txt
          path: raiwidgets/installed-requirements-dev.txt

      - name: Run tests
        run: |
          pytest -s -v --durations=10 --doctest-modules --junitxml=junit/test-results.xml --cov=${{ matrix.packageDirectory }} --cov-report=xml --cov-report=html
        working-directory: ${{ matrix.packageDirectory }}

      - name: Upload code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.packageDirectory }}-${{ matrix.pythonVersion}}-code-coverage-results
          path: ${{ matrix.packageDirectory }}-${{ matrix.pythonVersion}}/htmlcov
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

      - if: ${{ (matrix.operatingSystem == 'windows-latest') && (matrix.pythonVersion == '3.9') }}
        name: Upload to codecov
        id: codecovupload1
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ matrix.packageDirectory }}
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./${{ matrix.packageDirectory }}/coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - if: ${{ (steps.codecovupload1.outcome == 'failure') && (matrix.pythonVersion == '3.9') && (matrix.operatingSystem == 'windows-latest') }}
        name: Retry upload to codecov
        id: codecovupload2
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ${{ matrix.packageDirectory }}
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./${{ matrix.packageDirectory }}/coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Set codecov status
        if: ${{ (matrix.pythonVersion == '3.9') && (matrix.operatingSystem == 'windows-latest') }}
        shell: bash
        run: |
          if ${{ (steps.codecovupload1.outcome == 'success') || (steps.codecovupload2.outcome == 'success') }} ; then
            echo fine
          else
            exit 1
          fi
